query GetPromises {
  sentPromises {
    id
    content
    level
    dueDate
    direction
    sender {
      id
      displayName
      pictureUrl
    }
    receiver {
      id
      displayName
      pictureUrl
    }
    isAccepted
    completedAt
    canceledAt
    isShare
  }
  receivedPromises {
    id
    content
    level
    dueDate
    direction
    sender {
      id
      displayName
      pictureUrl
    }
    receiver {
      id
      displayName
      pictureUrl
    }
    isAccepted
    completedAt
    canceledAt
    isShare
  }
}

query GetPromise($id: String!) {
  promise(id: $id) {
    id
    content
    level
    dueDate
    direction
    sender {
      id
      displayName
      pictureUrl
    }
    receiver {
      id
      displayName
      pictureUrl
    }
    isAccepted
    completedAt
    canceledAt
    isShare
  }
}

mutation CreatePromise($input: CreatePromiseInput!) {
  createPromise(input: $input) {
    id
    content
    level
    dueDate
    sender {
      id
      displayName
      pictureUrl
    }
    receiver {
      id
      displayName
      pictureUrl
    }
  }
}

mutation AcceptPromise($id: ID!) {
  acceptPromise(id: $id) {
    id
    content
    level
    dueDate
    direction
    sender {
      id
      displayName
      pictureUrl
    }
    receiver {
      id
      displayName
      pictureUrl
    }
    isAccepted
    completedAt
  }
}

mutation RejectPromise($id: ID!) {
  rejectPromise(id: $id) {
    id
    content
    level
    dueDate
    direction
    sender {
      id
      displayName
      pictureUrl
    }
    receiver {
      id
      displayName
      pictureUrl
    }
    isAccepted
    completedAt
  }
}

mutation CompletePromise($id: ID!) {
  completePromise(id: $id) {
    id
    content
    level
    dueDate
    direction
    sender {
      id
      displayName
      pictureUrl
    }
    receiver {
      id
      displayName
      pictureUrl
    }
    isAccepted
    completedAt
  }
}

mutation CancelPromise($id: ID!) {
  cancelPromise(id: $id) {
    id
    content
    level
    dueDate
    direction
    sender {
      id
      displayName
      pictureUrl
    }
    receiver {
      id
      displayName
      pictureUrl
    }
    isAccepted
    completedAt
  }
}

mutation DeletePromise($id: ID!) {
  deletePromise(id: $id) {
    id
  }
}
