query GetPromises {
  promises {
    id
    content
    level
    dueDate
    direction
    sender {
      id
      displayName
      pictureUrl
    }
    receiver {
      id
      displayName
      pictureUrl
    }
    isAccepted
  }
}

query GetPromise($id: String!) {
  promise(id: $id) {
    id
    content
    level
    dueDate
    direction
    sender {
      id
      displayName
      pictureUrl
    }
    receiver {
      id
      displayName
      pictureUrl
    }
    isAccepted
    completedAt
  }
}


mutation CreatePromise($input: CreatePromiseInput!) {
  createPromise(input: $input) {
    id
    content
    level
    dueDate
    sender {
      id
      displayName
      pictureUrl
    }
    receiver {
      id
      displayName
      pictureUrl
    }
  }
}

mutation AcceptPromise($id: ID!, $receiverId: String!) {
  acceptPromise(id: $id, receiverId: $receiverId) {
    id
    content
    level
    dueDate
    direction
    sender {
      id
      displayName
      pictureUrl
    }
    receiver {
      id
      displayName
      pictureUrl
    }
  }
}

mutation RejectPromise($id: ID!) {
  rejectPromise(id: $id) {
    id
    content
    level
    dueDate
    direction
    sender {
      id
      displayName
      pictureUrl
    }
  }
}

mutation CompletePromise($id: ID!) {
  completePromise(id: $id) {
    id
    content
    level
    dueDate
    direction
    sender {
      id
      displayName
      pictureUrl
    }
    receiver {
      id
      displayName
      pictureUrl
    }
    
  }
}
