query GetUserByUserId($userId: String!) {
  userByUserId(userId: $userId) {
    id
    userId
    displayName
    pictureUrl
  }
}

mutation CreateUser($input: CreateUserInput!) {
  createUser(input: $input) {
    id
    userId
    displayName
    pictureUrl
  }
}
