query GetUserByUserId {
  userByUserId{
    id
    userId
    displayName
    pictureUrl
  }
}

mutation CreateUser($input: CreateUserInput!) {
  createUser(input: $input) {
    id
    userId
    displayName
    pictureUrl
  }
}
